// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAghJpWlDEqFn3cz4sxmg4s0QhIaDN98UQ',
    appId: '1:206293524129:web:657e936e4ab2a419a35ae0',
    messagingSenderId: '206293524129',
    projectId: 'campus-connect-10bd1',
    authDomain: 'campus-connect-10bd1.firebaseapp.com',
    storageBucket: 'campus-connect-10bd1.firebasestorage.app',
    measurementId: 'G-CH8GXX7X69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1cP5dtNIRhvUwv4SffpOFIJsGEIdByRs',
    appId: '1:206293524129:android:9b0fea3c4455e69da35ae0',
    messagingSenderId: '206293524129',
    projectId: 'campus-connect-10bd1',
    storageBucket: 'campus-connect-10bd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxR_UzWe4MYjFC_LN2No3M5sacAepIeRU',
    appId: '1:206293524129:ios:f003d3027868499ea35ae0',
    messagingSenderId: '206293524129',
    projectId: 'campus-connect-10bd1',
    storageBucket: 'campus-connect-10bd1.firebasestorage.app',
    iosBundleId: 'com.bahria.campusconnect.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxR_UzWe4MYjFC_LN2No3M5sacAepIeRU',
    appId: '1:206293524129:ios:f003d3027868499ea35ae0',
    messagingSenderId: '206293524129',
    projectId: 'campus-connect-10bd1',
    storageBucket: 'campus-connect-10bd1.firebasestorage.app',
    iosBundleId: 'com.bahria.campusconnect.campusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAghJpWlDEqFn3cz4sxmg4s0QhIaDN98UQ',
    appId: '1:206293524129:web:d5b2cd30aa98a743a35ae0',
    messagingSenderId: '206293524129',
    projectId: 'campus-connect-10bd1',
    authDomain: 'campus-connect-10bd1.firebaseapp.com',
    storageBucket: 'campus-connect-10bd1.firebasestorage.app',
    measurementId: 'G-9TLH0LY340',
  );
}
